--SQL USERS TABLE SETUP

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('Admin', 'Student', 'Parent', 'Driver'))
);


INSERT INTO users (username, password, role) VALUES
    ('admin_user',   'admin123',   'Admin'),
    ('student_alex', 'student123', 'Student'),
    ('parent_sara',  'parent123',  'Parent'),
    ('driver_raju',  'driver123',  'Driver'),
    ('driver_ramesh',  'driver123',  'Driver'),
    ('driver_suresh',  'driver123',  'Driver'),
    ('driver_mukesh',  'driver123',  'Driver'),
    ('student_arjun',  'student123', 'Student'),
    ('student_rahul',  'student123', 'Student'),
    ('student_vikram', 'student123', 'Student'),
    ('student_rohit',  'student123', 'Student'),
    ('student_karan',  'student123', 'Student'),
    ('student_aditya', 'student123', 'Student'),
    ('student_dhruv',  'student123', 'Student'),
    ('student_kabir',  'student123', 'Student'),
    ('student_pranay', 'student123', 'Student'),
    ('student_dev',    'student123', 'Student'),
    ('student_riya',   'student123', 'Student'),
    ('student_neha',   'student123', 'Student'),
    ('student_pooja',  'student123', 'Student'),
    ('student_anjali', 'student123', 'Student'),
    ('student_sneha',  'student123', 'Student'),
    ('student_isha',   'student123', 'Student'),
    ('student_meghna', 'student123', 'Student'),
    ('student_tanya',  'student123', 'Student'),
    ('student_kavya',  'student123', 'Student'),
    ('student_diya',   'student123', 'Student'),
    ('student_rishi',  'student123', 'Student'),
    ('student_suraj',  'student123', 'Student'),
    ('student_anil',   'student123', 'Student'),
    ('student_akash',  'student123', 'Student'),
    ('student_nitin',  'student123', 'Student'),
    ('student_ayush',  'student123', 'Student'),
    ('student_vishal', 'student123', 'Student'),
    ('student_amit',   'student123', 'Student'),
    ('student_sumit',  'student123', 'Student'),
    ('student_yash',   'student123', 'Student'),
    ('student_shreya', 'student123', 'Student'),
    ('student_simran', 'student123', 'Student'),
    ('student_mansi',  'student123', 'Student'),
    ('student_aarohi', 'student123', 'Student'),
    ('student_prachi', 'student123', 'Student'),
    ('student_nisha',  'student123', 'Student'),
    ('student_swati',  'student123', 'Student'),
    ('student_payal',  'student123', 'Student'),
    ('student_pallavi','student123', 'Student'),
    ('parent_sunil',   'parent123',  'Parent'),
    ('parent_rajesh',  'parent123',  'Parent'),
    ('parent_sanjay',  'parent123',  'Parent'),
    ('parent_ajay',    'parent123',  'Parent'),
    ('parent_vijay',   'parent123',  'Parent'),
    ('parent_ashok',   'parent123',  'Parent'),
    ('parent_prakash', 'parent123',  'Parent'),
    ('parent_naveen',  'parent123',  'Parent'),
    ('parent_dinesh',  'parent123',  'Parent'),
    ('parent_anand',   'parent123',  'Parent'),
    ('parent_geeta',   'parent123',  'Parent'),
    ('parent_sunita',  'parent123',  'Parent'),
    ('parent_rekha',   'parent123',  'Parent'),
    ('parent_seema',   'parent123',  'Parent'),
    ('parent_meena',   'parent123',  'Parent'),
    ('parent_kavita',  'parent123',  'Parent'),
    ('parent_sarita',  'parent123',  'Parent'),
    ('parent_punam',   'parent123',  'Parent'),
    ('parent_mamta',   'parent123',  'Parent'),
    ('parent_anita',   'parent123',  'Parent'),
    ('parent_manoj',   'parent123',  'Parent'),
    ('parent_ravi',    'parent123',  'Parent'),
    ('parent_mukesh',  'parent123',  'Parent'),
    ('parent_ram',     'parent123',  'Parent'),
    ('parent_shyam',   'parent123',  'Parent'),
    ('parent_harish',  'parent123',  'Parent'),
    ('parent_gopal',   'parent123',  'Parent'),
    ('parent_krishna', 'parent123',  'Parent'),
    ('parent_mahesh',  'parent123',  'Parent'),
    ('parent_kamal',   'parent123',  'Parent'),
    ('parent_sushma',  'parent123',  'Parent'),
    ('parent_renu',    'parent123',  'Parent'),
    ('parent_arti',    'parent123',  'Parent'),
    ('parent_jyoti',   'parent123',  'Parent'),
    ('parent_rani',    'parent123',  'Parent'),
    ('parent_usha',    'parent123',  'Parent'),
    ('parent_kiran',   'parent123',  'Parent'),
    ('parent_bhavna',  'parent123',  'Parent'),
    ('parent_vandana', 'parent123',  'Parent');